In [34]:
import pickle as pkl
import numpy as np

In [47]:
ohe_sex = pkl.load(open('day29_models/ohe_sex.pkl', 'rb'))
ohe_embarked = pkl.load(open('day29_models/ohe_embarked.pkl', 'rb'))
clf = pkl.load(open('day29_models/clf.pkl', 'rb'))

In [36]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype='object').reshape(1,7)

In [37]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [38]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [39]:
print(f"ohe_sex features_in: {ohe_sex.n_features_in_}")
print(f"ohe_embarked features_in: {ohe_embarked.n_features_in_}")

ohe_sex features_in: 1
ohe_embarked features_in: 1


In [40]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [41]:
test_input_embarked

array([[0., 0., 1.]])

In [42]:
test_input_age = test_input[:,2].reshape(1,1)

In [43]:
test_input_transformed = np.concatenate((
    test_input[:, [0, 3, 4, 5]], 
    test_input_age, 
    test_input_sex, 
    test_input_embarked
), axis=1)

In [44]:
test_input_transformed.shape

(1, 10)

In [48]:
clf.predict(test_input_transformed)

array([1])